spring:
  application:
    name: servicio-items
#  config:
#    import: optional:configserver:http://localhost:8888
server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE