spring:
  application:
    name: servicio-productos
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka